/// Onboarding vibe / interest chips (Instagram-style breadth).
abstract final class InterestVibesCatalog {
  InterestVibesCatalog._();

  static const List<String> all = [
    // Music & audio
    'Pop',
    'Hip hop',
    'R&B',
    'Rock',
    'Indie',
    'Electronic',
    'House',
    'Techno',
    'EDM',
    'Jazz',
    'Classical',
    'Country',
    'Latin music',
    'K-pop',
    'Afrobeats',
    'Reggae',
    'Soul',
    'Funk',
    'Metal',
    'Punk',
    'Lo-fi',
    'Live music',
    'DJ sets',
    'Singing',
    'Songwriting',
    'Guitar',
    'Piano',
    'Drums',
    'Podcasts',
    'Audiobooks',
    // Gaming
    'Gaming',
    'Mobile games',
    'Console gaming',
    'PC gaming',
    'Esports',
    'FPS',
    'Battle royale',
    'RPG',
    'MMO',
    'Strategy games',
    'Simulation games',
    'Sports games',
    'Racing games',
    'Fighting games',
    'Indie games',
    'Retro gaming',
    'VR gaming',
    'Streaming games',
    'Speedrunning',
    'Game design',
    'Minecraft',
    'Fortnite',
    'FIFA',
    'Call of Duty',
    'League of Legends',
  // Sports & fitness
    'Football',
    'Soccer',
    'Basketball',
    'Tennis',
    'Cricket',
    'Baseball',
    'Golf',
    'Boxing',
    'MMA',
    'Wrestling',
    'Volleyball',
    'Rugby',
    'Hockey',
    'Swimming',
    'Running',
    'Marathon',
    'Cycling',
    'Skateboarding',
    'Surfing',
    'Snowboarding',
    'Skiing',
    'Rock climbing',
    'Yoga',
    'Pilates',
    'Gym',
    'CrossFit',
    'Calisthenics',
    'Bodybuilding',
    'Martial arts',
    'Dance fitness',
    'Hiking',
    'Outdoor sports',
    'Motorsport',
    'Formula 1',
    'NBA',
    'Premier League',
    'UFC',
    // Food & drink
    'Food',
    'Cooking',
    'Baking',
    'Street food',
    'Fine dining',
    'Coffee',
    'Tea',
    'Wine',
    'Cocktails',
    'Mocktails',
    'Beer',
    'Vegan food',
    'Vegetarian',
    'BBQ',
    'Sushi',
    'Pizza',
    'Desserts',
    'Healthy eating',
    'Meal prep',
    'Food reviews',
    'Restaurants',
    'Brunch',
    'Farm to table',
    'Spicy food',
    'Seafood',
    // Travel
    'Travel',
    'Backpacking',
    'Luxury travel',
    'Road trips',
    'Beach vacations',
    'City breaks',
    'Adventure travel',
    'Solo travel',
    'Family travel',
    'Camping',
    'Van life',
    'Hotels',
    'Airbnb',
    'Airports',
    'Aviation',
    'Cruises',
    'National parks',
    'Europe travel',
    'Asia travel',
    'Africa travel',
    'Americas travel',
    // Fashion & beauty
    'Fashion',
    'Streetwear',
    'Luxury fashion',
    'Vintage fashion',
    'Sneakers',
    'Thrifting',
    'Makeup',
    'Skincare',
    'Haircare',
    'Nails',
    'Fragrance',
    'Jewelry',
    'Watches',
    'Sustainable fashion',
    'Runway',
    'Outfit inspo',
    'Menswear',
    'Womenswear',
    'Accessories',
    'Modeling',
    // Art & creativity
    'Art',
    'Drawing',
    'Painting',
    'Digital art',
    'Illustration',
    'Graphic design',
    'UI design',
    'Animation',
    '3D art',
    'Sculpture',
    'Calligraphy',
    'Photography',
    'Portrait photography',
    'Street photography',
    'Film photography',
    'Cinematography',
    'Filmmaking',
    'Writing',
    'Poetry',
    'Crafts',
    'DIY',
    'Knitting',
    'Woodworking',
    // Entertainment
    'Movies',
    'TV shows',
    'Netflix',
    'Anime',
    'Manga',
    'Comics',
    'Marvel',
    'Horror',
    'Sci-fi',
    'Romance films',
    'Documentaries',
    'True crime',
    'Reality TV',
    'Stand-up comedy',
    'Theater',
    'Broadway',
    'Concerts',
    'Festivals',
    'Award shows',
    'Celebrity news',
    'Memes',
    'Viral trends',
    // Tech & science
    'Tech',
    'AI',
    'Coding',
    'Startups',
    'Apple',
    'Android',
    'Gadgets',
    'Smart home',
    'Cybersecurity',
    'Crypto',
    'Web3',
    'NFTs',
    'Science',
    'Space',
    'Astronomy',
    'Physics',
    'Biology',
    'Psychology',
    'History',
    'Philosophy',
    'Engineering',
    'Robotics',
    'Electric vehicles',
    'Tesla',
    // Lifestyle & home
    'Fitness',
    'Wellness',
    'Meditation',
    'Mindfulness',
    'Self care',
    'Productivity',
    'Minimalism',
    'Interior design',
    'Home decor',
    'Gardening',
    'Plants',
    'Parenting',
    'Family',
    'Relationships',
    'Dating',
    'Weddings',
    'Luxury lifestyle',
    'Cars',
    'Motorcycles',
    'Real estate',
    'Personal finance',
    'Investing',
    'Entrepreneurship',
    'Side hustles',
    'Freelancing',
    // Social & learning
    'Education',
    'Languages',
    'Books',
    'Book clubs',
    'Public speaking',
    'Leadership',
    'Volunteering',
    'Climate action',
    'Sustainability',
    'Politics',
    'News',
    'Activism',
    'Charity',
    'Mental health',
    'LGBTQ+',
    'Culture',
    'History buff',
    // Pets & nature
    'Pets',
    'Dogs',
    'Cats',
    'Aquariums',
    'Birds',
    'Horses',
    'Wildlife',
    'Nature',
    'Ocean',
    'Mountains',
    'Forests',
    'Astrophotography',
    // Dance & performance
    'Dance',
    'Ballet',
    'Hip hop dance',
    'Salsa',
    'Ballroom',
    'TikTok dances',
    'Choreography',
    'Magic',
    'Cosplay',
    'Roleplay',
    // Niche & platform
    'Beauty tutorials',
    'GRWM',
    'Unboxing',
    'ASMR',
    'Reaction videos',
    'Vlogs',
    'Day in my life',
    'Study with me',
    'Motivation',
    'Sports highlights',
    'Fantasy sports',
    'Betting tips',
    'Collectibles',
    'Trading cards',
    'Sneaker resell',
    'Thrifting hauls',
    'Small business',
    'Content creation',
    'Influencer life',
    'Live streaming',
  ];

  static int get count => all.length;

  /// Splits [items] across [rowCount] horizontal rows (round-robin).
  static List<List<String>> rowsFor(
    List<String> items, {
    int rowCount = 6,
  }) {
    if (items.isEmpty || rowCount < 1) return [];
    final rows = List.generate(rowCount, (_) => <String>[]);
    for (var i = 0; i < items.length; i++) {
      rows[i % rowCount].add(items[i]);
    }
    return rows.where((r) => r.isNotEmpty).toList();
  }
}
